name: OnePlus_13T
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Maximize Disk Space
        uses: hugoalh/disk-space-optimizer-ghaction@v0.8.1
        with:
          operate_async: "True"
          operate_sudo: "True"
          general_include: ".+"
          general_exclude: |-
            ^GCC$
            ^G\+\+$
            Clang
            LLVM
          docker_include: ".+"
          docker_prune: "True"
          docker_clean: "True"
          apt_prune: "True"
          apt_clean: "True"
          homebrew_prune: "True"
          homebrew_clean: "True"
          npm_prune: "True"
          npm_clean: "True"
          os_swap: "False"

      - name: Organize build space
        uses: easimon/maximize-build-space@master
        with:
          swap-size-mb: 512
          
      - name: Configure Git
        run: |
          git config --global user.name "People-11"
          git config --global user.email "41558215+People-11@users.noreply.github.com"

      - name: Install repo tool
        run: |
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/repo
          chmod a+x ~/repo
          sudo mv ~/repo /usr/local/bin/repo

      - name: Initialize repo and sync
        run: |
          mkdir kernel_workspace && cd kernel_workspace
          repo init -u https://github.com/OnePlusOSS/kernel_manifest.git -b refs/heads/oneplus/sm8750 -m oneplus_13s.xml --depth=1
          repo sync -c --no-tags

      - name: Useful Patches
        run: |
          git clone https://github.com/People-11/13sKernel.git --depth=1
          cp -f ./13sKernel/patches/*.patch ./kernel_workspace/kernel_platform && cd kernel_workspace/kernel_platform
          patch -p0 -l < 01_armv8.7-a.patch
          patch -p0 -l < 02_noiostat.patch
          patch -p0 -l < 03_polly.patch
          patch -p0 -l < 04_lazyRCU.patch
          patch -p0 -l < 05_nomitigate.patch
          patch -p0 -l < 06_spdup_ioctl.patch
          patch -p0 -l < 07_opt_cpuidle.patch
          patch -p0 -l < 08_opt_memcpy.patch
          patch -p0 -l < 09_opt_memmove.patch
          patch -p0 -l < 10_opt_memset.patch
          patch -p0 -l < 11_opt_memutil.patch
          patch -p0 -l < 12_menu_cleanup.patch
          patch -p0 -l < 13_menu_rm_iowait_influ.patch
          patch -p0 -l < 14_disable_KFENCE_UBSAN.patch
          patch -p0 -l < 15_idle_mem_barrier.patch
          patch -p0 -l < 16_PM_Reduce_freeze_timeout_to_1.patch
          patch -p0 -l < 17_mbcache_Speedup_cache_entry_creation.patch
          patch -p0 -l < 18_arm64_lib_Optimize_memcmp.patch
          patch -p0 -l < 19_arm64_clear_page_ali_16b.patch
          patch -p0 -l < 20_arm64_disable_self-hosted_debug.patch
          patch -p0 -l < 21_arm64_CRC32_1.patch
          patch -p0 -l < 22_arm64_CRC32_2.patch
          patch -p0 -l < 23_arm64_CRC32_3.patch
          patch -p0 -l < 24_f2fs_ATGC.patch
          patch -p0 -l < 25_f2fs_reduce_timeout.patch
          patch -p0 -l < 26_f2fs_Use_copy_page.patch
          patch -p0 -l < 27_f2fs_Reduce_GC_thread_sleep_time.patch
          patch -p0 -l < 28_f2fs_set_ioprio.patch
          patch -p0 -l < 29_f2fs_Demote_GC_thread.patch
          patch -p0 -l < 30_fs_Reduce_cache_pressure.patch
          patch -p0 -l < 31_fs_Align_file_struct_8b.patch
          patch -p0 -l < 32_workqueue_Queue_everything.patch
          patch -p0 -l < 33_workqueue_Queue_everything1.patch
          patch -p0 -l < 34_workqueue_Queue_everything2.patch
          patch -p0 -l < 35_workqueue_Reduce_expensive_locks.patch
          patch -p0 -l < 36_locking_rwsem_spin_faster.patch
          patch -p0 -l < 37_sched_fair00.patch
          patch -p0 -l < 38_sched_fair01.patch
          patch -p0 -l < 39_sched_fair02.patch
          patch -p0 -l < 40_sched_fair03.patch
          patch -p0 -l < 41_sched_fair04.patch
          patch -p0 -l < 42_sched_fair05.patch
          patch -p0 -l < 43_sched_fair06.patch
          patch -p0 -l < 44_sched_fair07.patch
          patch -p0 -l < 45_sched_fair08.patch
          patch -p0 -l < 46_sched_fair_Set_asym_priority.patch
          patch -p0 -l < 47_sched_fair_Remove_unnecessary_goto.patch
          patch -p0 -l < 48_sched_fair_Simplify_continue_balancing.patch
          patch -p0 -l < 49_sched_fair_Simplify_update_sd_pick_busiest.patch
          patch -p0 -l < 50_sched_fair_Dont_compute_NUMA_Balancing.patch
          patch -p0 -l < 51_sched_fair_Dont_compute_overloaded.patch
          patch -p0 -l < 52_sched_Disable_TTWU_QUEUE.patch
          patch -p0 -l < 53_sched_Use_SCHED_RR.patch
          patch -p0 -l < 54_sched_Skip_barrier_in_ttwu.patch
          patch -p0 -l < 55_sched_topology_Optimize_topology_span_sane.patch
          patch -p0 -l < 56_sched_topology_improve_topology_span_sane_speed.patch
          patch -p0 -l < 57_sched_topology_Refine_topology_span_sane_speedup.patch
          patch -p0 -l < 58_sched_core_Prioritize_migrating.patch
          patch -p0 -l < 59_Disable_CACHE_HOT_BUDDY.patch
          patch -p0 -l < 60_mm_Omit_RCU_read_lock.patch
          patch -p0 -l < 61_mm_Disable_watermark_boosting.patch
          patch -p0 -l < 62_mm_Disable_proactive_compaction.patch
          patch -p0 -l < 63_mm_Dont_exclude_allocation_types.patch
          patch -p0 -l < 64_mm_Dont_reserve_memory.patch
          patch -p0 -l < 65_mm_Optimize_loop_reduce_redundant.patch
          patch -p0 -l < 66_selinux_Remove_audit_dependency.patch
          patch -p0 -l < 67_selinux_Avoid_dynamic_memory_allocation1.patch
          patch -p0 -l < 68_selinux_Avoid_dynamic_memory_allocation2.patch
          patch -p0 -l < 69_bpf_Avoid_allocating_small_buffers.patch
          patch -p0 -l < 70_profiling_disable_unnecessary_profiling.patch
          patch -p0 -l < 71_uid_sys_stats_stutter_fix.patch
          patch -p0 -l < 72_uid_sys_stats_Remove_dependency.patch
          patch -p0 -l < 73_alarmtimer_Minimize_wakeup_time.patch
          patch -p0 -l < 74_net_Prevent_NetlinkEvent_spam.patch
          patch -p0 -l < 75_drm_bridge_Avoid_dynamic_memory_allocation.patch
          patch -p0 -l < 77_ipv4_tcp_NODELAY.patch
          patch -p0 -l < 78_irqchip_Remove_pr_devel_message.patch
          patch -p0 -l < 79_rcu_Make_grace_period_unbound.patch
          patch -p0 -l < 80_kernfs_Avoid_dynamic_memory_allocation1.patch
          patch -p0 -l < 81_kernel_Avoid_dynamic_memory_allocation2.patch
          patch -p0 -l < 82_kernel_IRQ_affinity_masks1.patch
          patch -p0 -l < 83_kernel_IRQ_affinity_masks2.patch
          patch -p0 -l < 84_kernel_Fix_cpufreq_memory_leaks.patch
          patch -p0 -l < 85_kernel_gotosleep.patch
          patch -p0 -l < 86_treewide_Optimize_page_clearing.patch
          patch -p0 -l < 87_drivers_O3.patch
          patch -p0 -l < 88_zsmalloc_use_copy_page.patch
          patch -p0 -l < 89_media_synchronized_wake.patch
          patch -p0 -l < 90_Speedup_LZ4_Decompress.patch
          patch -p0 -l < 91_loop_Add_WQ_HIGHPRI.patch
          patch -p0 -l < 92_No_iosched.patch
          patch -p0 -l < 93_Reduce_vm_stat_interval.patch
          patch -p0 -l < 94_Debloat_some_vendor_modules.patch
          patch -p0 -l < 95_psi_disable_debug_output.patch
          patch -p0 -l < 96_riscv_Optimize_crc32.patch
           
      - name: Add Configuration Settings
        run: |
          cd kernel_workspace/kernel_platform
          echo 'CONFIG_AUTOFDO_CLANG=y' >> ./common/arch/arm64/configs/gki_defconfig
          echo 'CONFIG_LTO_CLANG_THIN=y' >> ./common/arch/arm64/configs/gki_defconfig
          echo '# CONFIG_TCP_CONG_CUBIC is not set' >> ./common/arch/arm64/configs/gki_defconfig
          echo 'CONFIG_DEFAULT_BBR=y' >> ./common/arch/arm64/configs/gki_defconfig
          echo 'CONFIG_WQ_POWER_EFFICIENT_DEFAULT=y' >> ./common/arch/arm64/configs/gki_defconfig
          echo 'CONFIG_SCHED_CLUSTER=y' >> ./common/arch/arm64/configs/gki_defconfig
          sed -i 's/^CONFIG_CPU_FREQ_GOV_POWERSAVE=.*/# CONFIG_CPU_FREQ_GOV_POWERSAVE is not set/' ./common/arch/arm64/configs/gki_defconfig
          sed -i 's/^CONFIG_CPU_FREQ_GOV_CONSERVATIVE=.*/# CONFIG_CPU_FREQ_GOV_CONSERVATIVE is not set/' ./common/arch/arm64/configs/gki_defconfig
          sed -i 's/^CONFIG_PPP=.*/# CONFIG_PPP is not set/' ./common/arch/arm64/configs/gki_defconfig
          sed -i 's/^CONFIG_BLK_DEV_NVME=.*/# CONFIG_BLK_DEV_NVME is not set/' ./common/arch/arm64/configs/gki_defconfig
          sed -i 's/^CONFIG_USB_NET_DRIVERS=.*/# CONFIG_USB_NET_DRIVERS is not set/' ./common/arch/arm64/configs/gki_defconfig
          sed -i 's/^CONFIG_PM_DEBUG=.*/# CONFIG_PM_DEBUG is not set/' ./common/arch/arm64/configs/gki_defconfig
          sed -i 's/^CONFIG_CRYPTO_LZO=.*/# CONFIG_CRYPTO_LZO is not set/' ./common/arch/arm64/configs/gki_defconfig
          sed -i '/^CONFIG_NET_SCH_/d' ./common/arch/arm64/configs/gki_defconfig && echo -e 'CONFIG_NET_SCH_FQ=y\nCONFIG_DEFAULT_FQ=y' >> ./common/arch/arm64/configs/gki_defconfig
          sed -i 's/check_defconfig//' ./common/build.config.gki
          sed -i 's/${scm_version}//' ./common/scripts/setlocalversion
          sed -i 's/-4k/-android15-Neko/g' ./common/arch/arm64/configs/gki_defconfig
          rm common/android/abi_gki_protected_exports_* && rm msm-kernel/android/abi_gki_protected_exports_*

      - name: Build Kernel
        run: |
          sudo apt install -y libelf-dev
          export PATH="$GITHUB_WORKSPACE/kernel_workspace/kernel_platform/prebuilts/clang/host/linux-x86/clang-r510928/bin:$PATH"
          cd kernel_workspace/kernel_platform/common
          make -j$(nproc --all) LLVM=1 ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- CC=clang RUSTC=../../prebuilts/rust/linux-x86/1.73.0b/bin/rustc PAHOLE=../../prebuilts/kernel-build-tools/linux-x86/bin/pahole LD=ld.lld HOSTLD=ld.lld O=out gki_defconfig all
         
      - name: Make AnyKernel3
        run: |
          git clone https://github.com/Kernel-SU/AnyKernel3.git --depth=1      
          rm -rf ./AnyKernel3/.git
          cp kernel_workspace/kernel_platform/common/out/arch/arm64/boot/Image ./AnyKernel3/
          cp kernel_workspace/kernel_platform/common/out/.config ./AnyKernel3/

      - name: Upload AnyKernel3
        uses: actions/upload-artifact@v4
        with:
          name: OnePlus_13T
          path: ./AnyKernel3/*
